# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: r2dbc-dto-projections
      POSTGRES_PASSWORD: r2dbc-dto-projections
      POSTGRES_DB: r2dbc-dto-projections_db
    ports:
      - 5433:5432
